### PR TITLE
RUP -  Cambia detalle en wait

### PR DESCRIPTION
**Pull request by palita1991**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/RUP-318

### Funcionalidad desarrollada 

1. Se hizo un cambio ya que fallaron unos test en la ultima corrida 
BUILD NUMBER: [6709](http://condorpiedra.andes.gob.ar:85/6709/mochawesome.html) CYPRESS RUN: [5562](https://dashboard.cypress.io/projects/xr7gft/runs/5562/specs)

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [6711](http://condorpiedra.andes.gob.ar:85/6711/mochawesome.html)
CYPRESS RUN: [5564](https://dashboard.cypress.io/projects/xr7gft/runs/5564/specs)
TEST START: 2022-06-29T18:45:41.135Z
TOTAL: 408
SUCCESS: 401
FAIL: 3
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [6717](http://condorpiedra.andes.gob.ar:85/6717/mochawesome.html)
CYPRESS RUN: [5570](https://dashboard.cypress.io/projects/xr7gft/runs/5570/specs)
TEST START: 2022-06-30T11:40:13.401Z
TOTAL: 273
SUCCESS: 210
FAIL: 61
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [6721](http://condorpiedra.andes.gob.ar:85/6721/mochawesome.html)
CYPRESS RUN: [5574](https://dashboard.cypress.io/projects/xr7gft/runs/5574/specs)
TEST START: 2022-06-30T12:57:46.368Z
TOTAL: 408
SUCCESS: 402
FAIL: 2
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [6739](http://condorpiedra.andes.gob.ar:85/6739/mochawesome.html)
CYPRESS RUN: [5592](https://dashboard.cypress.io/projects/xr7gft/runs/5592/specs)
TEST START: 2022-06-30T19:16:42.645Z
TOTAL: 408
SUCCESS: 403
FAIL: 1
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [6835](http://condorpiedra.andes.gob.ar:85/6835/mochawesome.html)
CYPRESS RUN: [5683](https://dashboard.cypress.io/projects/xr7gft/runs/5683/specs)
TEST START: 2022-07-08T17:50:55.356Z
TOTAL: 375
SUCCESS: 360
FAIL: 13
SKIPPED: 2

**Comment by martinebucarey** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7532](http://condorpiedra.andes.gob.ar:85/7532/mochawesome.html)
CYPRESS RUN: [6339](https://dashboard.cypress.io/projects/xr7gft/runs/6339/specs)
TEST START: 2022-08-29T15:47:22.971Z
TOTAL: 335
SUCCESS: 315
FAIL: 19
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7659](http://condorpiedra.andes.gob.ar:85/7659/mochawesome.html)
CYPRESS RUN: [6590](https://dashboard.cypress.io/projects/xr7gft/runs/6590/specs)
TEST START: 2022-09-19T11:42:09.929Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7660](http://condorpiedra.andes.gob.ar:85/7660/mochawesome.html)
CYPRESS RUN: [6591](https://dashboard.cypress.io/projects/xr7gft/runs/6591/specs)
TEST START: 2022-09-19T12:23:02.456Z
TOTAL: 4
SUCCESS: 2
FAIL: 2
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7661](http://condorpiedra.andes.gob.ar:85/7661/mochawesome.html)
CYPRESS RUN: [6592](https://dashboard.cypress.io/projects/xr7gft/runs/6592/specs)
TEST START: 2022-09-19T12:37:52.882Z
TOTAL: 4
SUCCESS: 4
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7662](http://condorpiedra.andes.gob.ar:85/7662/mochawesome.html)
CYPRESS RUN: [6593](https://dashboard.cypress.io/projects/xr7gft/runs/6593/specs)
TEST START: 2022-09-19T12:41:23.171Z
TOTAL: 4
SUCCESS: 4
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mpalavecino  
BUILD NUMBER: [7663](http://condorpiedra.andes.gob.ar:85/7663/mochawesome.html)
CYPRESS RUN: [6594](https://dashboard.cypress.io/projects/xr7gft/runs/6594/specs)
TEST START: 2022-09-19T12:44:05.341Z
TOTAL: 3
SUCCESS: 3
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7697](http://condorpiedra.andes.gob.ar:85/7697/mochawesome.html)
CYPRESS RUN: [6688](https://dashboard.cypress.io/projects/xr7gft/runs/6688/specs)
TEST START: 2022-09-27T18:19:18.836Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7797](http://condorpiedra.andes.gob.ar:85/7797/mochawesome.html)
CYPRESS RUN: [6935](https://dashboard.cypress.io/projects/xr7gft/runs/6935/specs)
TEST START: 2022-10-19T18:15:34.371Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7798](http://condorpiedra.andes.gob.ar:85/7798/mochawesome.html)
CYPRESS RUN: [6936](https://dashboard.cypress.io/projects/xr7gft/runs/6936/specs)
TEST START: 2022-10-19T18:19:40.643Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7805](http://condorpiedra.andes.gob.ar:85/7805/mochawesome.html)
CYPRESS RUN: [6942](https://dashboard.cypress.io/projects/xr7gft/runs/6942/specs)
TEST START: 2022-10-20T15:58:07.008Z
TOTAL: 398
SUCCESS: 389
FAIL: 8
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7814](http://condorpiedra.andes.gob.ar:85/7814/mochawesome.html)
CYPRESS RUN: [6951](https://dashboard.cypress.io/projects/xr7gft/runs/6951/specs)
TEST START: 2022-10-21T13:21:56.445Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7840](http://condorpiedra.andes.gob.ar:85/7840/mochawesome.html)
CYPRESS RUN: [6975](https://dashboard.cypress.io/projects/xr7gft/runs/6975/specs)
TEST START: 2022-10-25T15:44:04.014Z
TOTAL: 406
SUCCESS: 382
FAIL: 23
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7841](http://condorpiedra.andes.gob.ar:85/7841/mochawesome.html)
CYPRESS RUN: [6976](https://dashboard.cypress.io/projects/xr7gft/runs/6976/specs)
TEST START: 2022-10-25T15:58:40.546Z
TOTAL: 406
SUCCESS: 402
FAIL: 3
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7842](http://condorpiedra.andes.gob.ar:85/7842/mochawesome.html)
CYPRESS RUN: [6977](https://dashboard.cypress.io/projects/xr7gft/runs/6977/specs)
TEST START: 2022-10-25T18:04:44.933Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [7844](http://condorpiedra.andes.gob.ar:85/7844/mochawesome.html)
CYPRESS RUN: [6979](https://dashboard.cypress.io/projects/xr7gft/runs/6979/specs)
TEST START: 2022-10-25T18:55:47.226Z
TOTAL: 406
SUCCESS: 388
FAIL: 17
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7880](http://condorpiedra.andes.gob.ar:85/7880/mochawesome.html)
CYPRESS RUN: [7020](https://dashboard.cypress.io/projects/xr7gft/runs/7020/specs)
TEST START: 2022-11-08T17:57:31.317Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7881](http://condorpiedra.andes.gob.ar:85/7881/mochawesome.html)
CYPRESS RUN: [7023](https://dashboard.cypress.io/projects/xr7gft/runs/7023/specs)
TEST START: 2022-11-08T18:03:55.062Z
TOTAL: 406
SUCCESS: 390
FAIL: 15
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7882](http://condorpiedra.andes.gob.ar:85/7882/mochawesome.html)
CYPRESS RUN: [7026](https://dashboard.cypress.io/projects/xr7gft/runs/7026/specs)
TEST START: 2022-11-08T18:27:18.417Z
TOTAL: 397
SUCCESS: 396
FAIL: 0
SKIPPED: 1

**Review by negro89 — APPROVED** [review]

**Pull request merged**
