### PR TITLE
Epidemiologia - No se permite editar FIS

### PR DESCRIPTION
**Pull request by martinebucarey**
### Requerimiento
Actualizar test de edición de ficha

### Funcionalidad desarrollada 

1. En la ficha actual el campo fis es readonly, no se puede editar. Se realiza el cambio en el test
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6698](http://condorpiedra.andes.gob.ar:85/6698/mochawesome.html)
CYPRESS RUN: [5552](https://dashboard.cypress.io/projects/xr7gft/runs/5552/specs)
TEST START: 2022-06-29T13:29:13.371Z
TOTAL: 408
SUCCESS: 403
FAIL: 1
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6703](http://condorpiedra.andes.gob.ar:85/6703/mochawesome.html)
CYPRESS RUN: [5556](https://dashboard.cypress.io/projects/xr7gft/runs/5556/specs)
TEST START: 2022-06-29T14:38:00.230Z
TOTAL: 408
SUCCESS: 403
FAIL: 1
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [6705](http://condorpiedra.andes.gob.ar:85/6705/mochawesome.html)
CYPRESS RUN: [5558](https://dashboard.cypress.io/projects/xr7gft/runs/5558/specs)
TEST START: 2022-06-29T15:34:30.043Z
TOTAL: 408
SUCCESS: 397
FAIL: 7
SKIPPED: 4

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7494](http://condorpiedra.andes.gob.ar:85/7494/mochawesome.html)
CYPRESS RUN: [6301](https://dashboard.cypress.io/projects/xr7gft/runs/6301/specs)
TEST START: 2022-08-23T15:12:33.863Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7499](http://condorpiedra.andes.gob.ar:85/7499/mochawesome.html)
CYPRESS RUN: [6305](https://dashboard.cypress.io/projects/xr7gft/runs/6305/specs)
TEST START: 2022-08-23T15:56:45.927Z
TOTAL: 397
SUCCESS: 391
FAIL: 5
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7503](http://condorpiedra.andes.gob.ar:85/7503/mochawesome.html)
CYPRESS RUN: [6308](https://dashboard.cypress.io/projects/xr7gft/runs/6308/specs)
TEST START: 2022-08-23T17:13:08.987Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7504](http://condorpiedra.andes.gob.ar:85/7504/mochawesome.html)
CYPRESS RUN: [6309](https://dashboard.cypress.io/projects/xr7gft/runs/6309/specs)
TEST START: 2022-08-23T17:49:42.657Z
TOTAL: 377
SUCCESS: 369
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7509](http://condorpiedra.andes.gob.ar:85/7509/mochawesome.html)
CYPRESS RUN: [6316](https://dashboard.cypress.io/projects/xr7gft/runs/6316/specs)
TEST START: 2022-08-24T13:41:35.905Z
TOTAL: 99
SUCCESS: 0
FAIL: 99
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7513](http://condorpiedra.andes.gob.ar:85/7513/mochawesome.html)
CYPRESS RUN: [6320](https://dashboard.cypress.io/projects/xr7gft/runs/6320/specs)
TEST START: 2022-08-24T16:56:43.298Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7514](http://condorpiedra.andes.gob.ar:85/7514/mochawesome.html)
CYPRESS RUN: [6321](https://dashboard.cypress.io/projects/xr7gft/runs/6321/specs)
TEST START: 2022-08-24T17:14:34.243Z
TOTAL: 376
SUCCESS: 366
FAIL: 9
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7515](http://condorpiedra.andes.gob.ar:85/7515/mochawesome.html)
CYPRESS RUN: [6322](https://dashboard.cypress.io/projects/xr7gft/runs/6322/specs)
TEST START: 2022-08-24T17:39:38.875Z
TOTAL: 348
SUCCESS: 340
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7516](http://condorpiedra.andes.gob.ar:85/7516/mochawesome.html)
CYPRESS RUN: [6323](https://dashboard.cypress.io/projects/xr7gft/runs/6323/specs)
TEST START: 2022-08-24T18:05:57.245Z
TOTAL: 390
SUCCESS: 374
FAIL: 15
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7520](http://condorpiedra.andes.gob.ar:85/7520/mochawesome.html)
CYPRESS RUN: [6327](https://dashboard.cypress.io/projects/xr7gft/runs/6327/specs)
TEST START: 2022-08-25T13:32:19.969Z
TOTAL: 406
SUCCESS: 399
FAIL: 6
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7522](http://condorpiedra.andes.gob.ar:85/7522/mochawesome.html)
CYPRESS RUN: [6329](https://dashboard.cypress.io/projects/xr7gft/runs/6329/specs)
TEST START: 2022-08-25T14:23:28.044Z
TOTAL: 315
SUCCESS: 306
FAIL: 8
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7523](http://condorpiedra.andes.gob.ar:85/7523/mochawesome.html)
CYPRESS RUN: [6330](https://dashboard.cypress.io/projects/xr7gft/runs/6330/specs)
TEST START: 2022-08-25T15:06:21.450Z
TOTAL: 406
SUCCESS: 398
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [7526](http://condorpiedra.andes.gob.ar:85/7526/mochawesome.html)
CYPRESS RUN: [6333](https://dashboard.cypress.io/projects/xr7gft/runs/6333/specs)
TEST START: 2022-08-26T13:15:35.082Z
TOTAL: 406
SUCCESS: 400
FAIL: 5
SKIPPED: 1

**Comment by MarianoCampetella** [comment]
Todos los tests de la clase ficha-epidemiologica.spec.ts están fallando. Este PR está significativamente desactualizado en relación con los cambios recientes en las fichas epidemiológicas. Será necesario evaluar si conviene cerrarlo o corregirlo por completo.

**Pull request closed without merging**
