### PR TITLE
TOP: cambios en tests para nuevo control de solicitudes duplicadas

### PR DESCRIPTION
**Pull request by juuliotero**
### Requerimiento
Adaptar los tests para el nuevo control de solicitudes duplicadas

### Funcionalidad desarrollada 

1. Se cambian tipos de prestaciones destino en tests de top

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [3610](http://condorpiedra.andes.gob.ar:85/3610/mochawesome.html)
CYPRESS RUN: [2691](https://dashboard.cypress.io/projects/xr7gft/runs/2691/specs)
TEST START: 2021-03-19T18:29:51.037Z
TOTAL: 363
SUCCESS: 361
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [3611](http://condorpiedra.andes.gob.ar:85/3611/mochawesome.html)
CYPRESS RUN: [2692](https://dashboard.cypress.io/projects/xr7gft/runs/2692/specs)
TEST START: 2021-03-19T18:41:23.164Z
TOTAL: 363
SUCCESS: 355
FAIL: 8
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [3612](http://condorpiedra.andes.gob.ar:85/3612/mochawesome.html)
CYPRESS RUN: [2693](https://dashboard.cypress.io/projects/xr7gft/runs/2693/specs)
TEST START: 2021-03-19T18:59:25.548Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

**Review by palita1991 — APPROVED** [review]

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [3748](http://condorpiedra.andes.gob.ar:85/3748/mochawesome.html)
CYPRESS RUN: [2814](https://dashboard.cypress.io/projects/xr7gft/runs/2814/specs)
TEST START: 2021-04-13T13:19:05.228Z
TOTAL: 322
SUCCESS: 311
FAIL: 11
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: jotero  
BUILD NUMBER: [3749](http://condorpiedra.andes.gob.ar:85/3749/mochawesome.html)
CYPRESS RUN: [2815](https://dashboard.cypress.io/projects/xr7gft/runs/2815/specs)
TEST START: 2021-04-13T13:37:39.832Z
TOTAL: 363
SUCCESS: 363
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [3892](http://condorpiedra.andes.gob.ar:85/3892/mochawesome.html)
CYPRESS RUN: [2950](https://dashboard.cypress.io/projects/xr7gft/runs/2950/specs)
TEST START: 2021-04-29T13:08:46.331Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

**Pull request merged**
