### PR TITLE
(CIT-210) Nuevo mockup Reasignación de turnos

### PR DESCRIPTION
**Pull request by JuanIRamirez**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-210

### Funcionalidad desarrollada 

1.  Se modificó test gestor_agenda.spec.ts de acuerdo al nuevo mockup.
2.  Test: suspender agenda disponible con turno y reasignarlo.
3.  Test: suspender turno de agenda publicada.

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9610](http://condorpiedra.andes.gob.ar:85/9610/mochawesome.html)
CYPRESS RUN: [8726](https://dashboard.cypress.io/projects/xr7gft/runs/8726/specs)
TEST START: 2023-09-13T13:29:24.895Z
TOTAL: 378
SUCCESS: 370
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9611](http://condorpiedra.andes.gob.ar:85/9611/mochawesome.html)
CYPRESS RUN: [8727](https://dashboard.cypress.io/projects/xr7gft/runs/8727/specs)
TEST START: 2023-09-13T13:43:46.713Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9694](http://condorpiedra.andes.gob.ar:85/9694/mochawesome.html)
CYPRESS RUN: [8806](https://dashboard.cypress.io/projects/xr7gft/runs/8806/specs)
TEST START: 2023-09-28T13:07:09.148Z
TOTAL: 379
SUCCESS: 371
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9697](http://condorpiedra.andes.gob.ar:85/9697/mochawesome.html)
CYPRESS RUN: [8809](https://dashboard.cypress.io/projects/xr7gft/runs/8809/specs)
TEST START: 2023-09-28T13:43:43.470Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9769](http://condorpiedra.andes.gob.ar:85/9769/mochawesome.html)
CYPRESS RUN: [8879](https://dashboard.cypress.io/projects/xr7gft/runs/8879/specs)
TEST START: 2023-10-12T12:16:54.855Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9771](http://condorpiedra.andes.gob.ar:85/9771/mochawesome.html)
CYPRESS RUN: [8881](https://dashboard.cypress.io/projects/xr7gft/runs/8881/specs)
TEST START: 2023-10-12T18:27:01.774Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9773](http://condorpiedra.andes.gob.ar:85/9773/mochawesome.html)
CYPRESS RUN: [8883](https://dashboard.cypress.io/projects/xr7gft/runs/8883/specs)
TEST START: 2023-10-13T13:02:32.248Z
TOTAL: 403
SUCCESS: 398
FAIL: 3
SKIPPED: 2

**Comment by negro89** [comment]
Tests al 15/05/24
image

**Pull request merged**
