### PR TITLE
IN - Deshacer internación

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
Correccion de casos de test según últimos cambios

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [9232](http://condorpiedra.andes.gob.ar:85/9232/mochawesome.html)
CYPRESS RUN: [8378](https://dashboard.cypress.io/projects/xr7gft/runs/8378/specs)
TEST START: 2023-07-20T12:54:01.768Z
TOTAL: 331
SUCCESS: 315
FAIL: 14
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [9233](http://condorpiedra.andes.gob.ar:85/9233/mochawesome.html)
CYPRESS RUN: [8379](https://dashboard.cypress.io/projects/xr7gft/runs/8379/specs)
TEST START: 2023-07-20T13:06:02.514Z
TOTAL: 403
SUCCESS: 395
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [9235](http://condorpiedra.andes.gob.ar:85/9235/mochawesome.html)
CYPRESS RUN: [8381](https://dashboard.cypress.io/projects/xr7gft/runs/8381/specs)
TEST START: 2023-07-20T14:28:17.163Z
TOTAL: 403
SUCCESS: 389
FAIL: 12
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [9238](http://condorpiedra.andes.gob.ar:85/9238/mochawesome.html)
CYPRESS RUN: [8384](https://dashboard.cypress.io/projects/xr7gft/runs/8384/specs)
TEST START: 2023-07-21T14:12:12.773Z
TOTAL: 355
SUCCESS: 347
FAIL: 6
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [9239](http://condorpiedra.andes.gob.ar:85/9239/mochawesome.html)
CYPRESS RUN: [8385](https://dashboard.cypress.io/projects/xr7gft/runs/8385/specs)
TEST START: 2023-07-21T14:27:26.216Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Pull request merged**
