### PR TITLE
FICHA EPIDEMIOLOGICA: Test para ficha

### PR DESCRIPTION
**Pull request by martinebucarey**
### Requerimiento
https://proyectos.andes.gob.ar/browse/EP-14

### Funcionalidad desarrollada 

1. Se crean test para crear/editar ficha de tipo covid 19.
2. Se agrega el formulario a la base de datos.
3. Se agrega el comando plexIcon.
4. Se agregan comandos usados al index.

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [3371](http://condorpiedra.andes.gob.ar:85/3371/mochawesome.html)
CYPRESS RUN: [2474](https://dashboard.cypress.io/projects/xr7gft/runs/2474/specs)
TEST START: 2021-02-19T16:21:56.078Z
TOTAL: 361
SUCCESS: 358
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [3375](http://condorpiedra.andes.gob.ar:85/3375/mochawesome.html)
CYPRESS RUN: [2478](https://dashboard.cypress.io/projects/xr7gft/runs/2478/specs)
TEST START: 2021-02-19T16:47:10.154Z
TOTAL: 7
SUCCESS: 7
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [3376](http://condorpiedra.andes.gob.ar:85/3376/mochawesome.html)
CYPRESS RUN: [2479](https://dashboard.cypress.io/projects/xr7gft/runs/2479/specs)
TEST START: 2021-02-19T16:58:09.179Z
TOTAL: 361
SUCCESS: 360
FAIL: 0
SKIPPED: 1

**Review by palita1991 — APPROVED** [review]

**Review by sychus — APPROVED** [review]
great!

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [3479](http://condorpiedra.andes.gob.ar:85/3479/mochawesome.html)
CYPRESS RUN: [2573](https://dashboard.cypress.io/projects/xr7gft/runs/2573/specs)
TEST START: 2021-03-02T17:53:35.457Z
TOTAL: 361
SUCCESS: 351
FAIL: 9
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [3480](http://condorpiedra.andes.gob.ar:85/3480/mochawesome.html)
CYPRESS RUN: [2574](https://dashboard.cypress.io/projects/xr7gft/runs/2574/specs)
TEST START: 2021-03-02T18:23:21.748Z
TOTAL: 361
SUCCESS: 360
FAIL: 0
SKIPPED: 1

**Pull request merged**
