### PR TITLE
IN - Agrega permisos de CDA para internación

### PR DESCRIPTION
**Pull request by ma7payne**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/IN-281

### Funcionalidad desarrollada 

1.  En mapa-camas.js se agrega el campo 'cda:*' en los permisos del usuario de prueba

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Review by Fabio-Ramirez — APPROVED** [review]

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10098](http://condorpiedra.andes.gob.ar:85/10098/mochawesome.html)
CYPRESS RUN: [9206](https://dashboard.cypress.io/projects/xr7gft/runs/9206/specs)
TEST START: 2023-12-20T17:21:43.967Z
TOTAL: 406
SUCCESS: 400
FAIL: 4
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10099](http://condorpiedra.andes.gob.ar:85/10099/mochawesome.html)
CYPRESS RUN: [9207](https://dashboard.cypress.io/projects/xr7gft/runs/9207/specs)
TEST START: 2023-12-20T17:37:08.917Z
TOTAL: 380
SUCCESS: 369
FAIL: 9
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10100](http://condorpiedra.andes.gob.ar:85/10100/mochawesome.html)
CYPRESS RUN: [9208](https://dashboard.cypress.io/projects/xr7gft/runs/9208/specs)
TEST START: 2023-12-20T18:07:55.773Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10103](http://condorpiedra.andes.gob.ar:85/10103/mochawesome.html)
CYPRESS RUN: [9211](https://dashboard.cypress.io/projects/xr7gft/runs/9211/specs)
TEST START: 2023-12-20T19:10:18.537Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10107](http://condorpiedra.andes.gob.ar:85/10107/mochawesome.html)
CYPRESS RUN: [9215](https://dashboard.cypress.io/projects/xr7gft/runs/9215/specs)
TEST START: 2023-12-21T16:55:19.692Z
TOTAL: 344
SUCCESS: 339
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10108](http://condorpiedra.andes.gob.ar:85/10108/mochawesome.html)
CYPRESS RUN: [9216](https://dashboard.cypress.io/projects/xr7gft/runs/9216/specs)
TEST START: 2023-12-21T17:54:44.404Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10109](http://condorpiedra.andes.gob.ar:85/10109/mochawesome.html)
CYPRESS RUN: [9217](https://dashboard.cypress.io/projects/xr7gft/runs/9217/specs)
TEST START: 2023-12-21T18:10:51.082Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10122](http://condorpiedra.andes.gob.ar:85/10122/mochawesome.html)
CYPRESS RUN: [9230](https://dashboard.cypress.io/projects/xr7gft/runs/9230/specs)
TEST START: 2023-12-22T18:44:06.166Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10135](http://condorpiedra.andes.gob.ar:85/10135/mochawesome.html)
CYPRESS RUN: [9243](https://dashboard.cypress.io/projects/xr7gft/runs/9243/specs)
TEST START: 2024-01-02T15:06:18.352Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10136](http://condorpiedra.andes.gob.ar:85/10136/mochawesome.html)
CYPRESS RUN: [9244](https://dashboard.cypress.io/projects/xr7gft/runs/9244/specs)
TEST START: 2024-01-02T15:41:25.907Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10137](http://condorpiedra.andes.gob.ar:85/10137/mochawesome.html)
CYPRESS RUN: [9245](https://dashboard.cypress.io/projects/xr7gft/runs/9245/specs)
TEST START: 2024-01-02T16:46:33.770Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10140](http://condorpiedra.andes.gob.ar:85/10140/mochawesome.html)
CYPRESS RUN: [9248](https://dashboard.cypress.io/projects/xr7gft/runs/9248/specs)
TEST START: 2024-01-03T11:34:08.084Z
TOTAL: 406
SUCCESS: 393
FAIL: 11
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10141](http://condorpiedra.andes.gob.ar:85/10141/mochawesome.html)
CYPRESS RUN: [9249](https://dashboard.cypress.io/projects/xr7gft/runs/9249/specs)
TEST START: 2024-01-03T11:59:25.728Z
TOTAL: 393
SUCCESS: 385
FAIL: 7
SKIPPED: 1

**Pull request merged**
