### PR TITLE
CIT - Implementa selector de financiadores

### PR DESCRIPTION
**Pull request by ma7payne**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/CIT-214

### Funcionalidad desarrollada 

1. Crea reglas para nuevo selector en punto_inicio.specs
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9703](http://condorpiedra.andes.gob.ar:85/9703/mochawesome.html)
CYPRESS RUN: [8815](https://dashboard.cypress.io/projects/xr7gft/runs/8815/specs)
TEST START: 2023-09-29T13:19:11.758Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [9704](http://condorpiedra.andes.gob.ar:85/9704/mochawesome.html)
CYPRESS RUN: [8816](https://dashboard.cypress.io/projects/xr7gft/runs/8816/specs)
TEST START: 2023-09-29T13:39:29.629Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10072](http://condorpiedra.andes.gob.ar:85/10072/mochawesome.html)
CYPRESS RUN: [9180](https://dashboard.cypress.io/projects/xr7gft/runs/9180/specs)
TEST START: 2023-12-19T16:30:33.335Z
TOTAL: 96
SUCCESS: 0
FAIL: 96
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10077](http://condorpiedra.andes.gob.ar:85/10077/mochawesome.html)
CYPRESS RUN: [9185](https://dashboard.cypress.io/projects/xr7gft/runs/9185/specs)
TEST START: 2023-12-19T18:02:02.920Z
TOTAL: 405
SUCCESS: 402
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mchiappe  
BUILD NUMBER: [10079](http://condorpiedra.andes.gob.ar:85/10079/mochawesome.html)
CYPRESS RUN: [9187](https://dashboard.cypress.io/projects/xr7gft/runs/9187/specs)
TEST START: 2023-12-19T18:22:21.137Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Pull request merged**
