### PR TITLE
TOP: Verifica generación de historial de solicitud

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/TOP-85
### Funcionalidad desarrollada 

1. Verifica generación de historial de solicitud
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### CODE REVIEW

**Comment by liquid36** [comment]
BUILD NUMBER: [1800](http://condorpiedra.andes.gob.ar:85/1800/mochawesome.html)
TEST START: 2020-09-15T12:47:03.898Z
TOTAL: 296
SUCCESS: 287
FAIL: 8
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [1801](http://condorpiedra.andes.gob.ar:85/1801/mochawesome.html)
TEST START: 2020-09-15T13:10:57.921Z
TOTAL: 297
SUCCESS: 296
FAIL: 0
SKIPPED: 1

**Review by palita1991 — CHANGES_REQUESTED** [review]
@plammel Estaría bueno ademas de verificar la **"acción"** sea correcta, hacer lo mismo con las **"observaciones"**

**Comment by liquid36** [comment]
BUILD NUMBER: [1910](http://condorpiedra.andes.gob.ar:85/1910/mochawesome.html)
TEST START: 2020-09-22T17:03:01.662Z
TOTAL: 297
SUCCESS: 288
FAIL: 8
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [1911](http://condorpiedra.andes.gob.ar:85/1911/mochawesome.html)
TEST START: 2020-09-22T17:40:30.943Z
TOTAL: 293
SUCCESS: 287
FAIL: 5
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [1916](http://condorpiedra.andes.gob.ar:85/1916/mochawesome.html)
TEST START: 2020-09-22T18:14:33.691Z
TOTAL: 214
SUCCESS: 203
FAIL: 10
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [1990](http://condorpiedra.andes.gob.ar:85/1990/mochawesome.html)
TEST START: 2020-09-29T19:03:10.278Z
TOTAL: 301
SUCCESS: 300
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
BUILD NUMBER: [2058](http://condorpiedra.andes.gob.ar:85/2058/mochawesome.html)
TEST START: 2020-10-05T17:56:45.024Z
TOTAL: 313
SUCCESS: 312
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [2059](http://condorpiedra.andes.gob.ar:85/2059/mochawesome.html)
TEST START: 2020-10-05T18:12:03.253Z
TOTAL: 313
SUCCESS: 312
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [2060](http://condorpiedra.andes.gob.ar:85/2060/mochawesome.html)
TEST START: 2020-10-05T18:15:12.615Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [2061](http://condorpiedra.andes.gob.ar:85/2061/mochawesome.html)
TEST START: 2020-10-05T18:27:31.719Z
TOTAL: 313
SUCCESS: 312
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [2062](http://condorpiedra.andes.gob.ar:85/2062/mochawesome.html)
TEST START: 2020-10-05T18:40:44.488Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
BUILD NUMBER: [2161](http://condorpiedra.andes.gob.ar:85/2161/mochawesome.html)
TEST START: 2020-10-09T18:16:37.822Z
TOTAL: 316
SUCCESS: 315
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [2241](http://condorpiedra.andes.gob.ar:85/2241/mochawesome.html)
CYPRESS RUN: [1419](https://dashboard.cypress.io/projects/xr7gft/runs/1419/specs)
TEST START: 2020-10-16T18:49:20.159Z
TOTAL: 251
SUCCESS: 233
FAIL: 18
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [2246](http://condorpiedra.andes.gob.ar:85/2246/mochawesome.html)
CYPRESS RUN: [1424](https://dashboard.cypress.io/projects/xr7gft/runs/1424/specs)
TEST START: 2020-10-19T11:55:27.766Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [2248](http://condorpiedra.andes.gob.ar:85/2248/mochawesome.html)
CYPRESS RUN: [1426](https://dashboard.cypress.io/projects/xr7gft/runs/1426/specs)
TEST START: 2020-10-19T13:24:53.663Z
TOTAL: 322
SUCCESS: 322
FAIL: 0
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: cceleste  
BUILD NUMBER: [2277](http://condorpiedra.andes.gob.ar:85/2277/mochawesome.html)
CYPRESS RUN: [1450](https://dashboard.cypress.io/projects/xr7gft/runs/1450/specs)
TEST START: 2020-10-20T17:40:05.020Z
TOTAL: 323
SUCCESS: 323
FAIL: 0
SKIPPED: 0

**Review by kroce — APPROVED** [review]

**Review by palita1991 — APPROVED** [review]

**Pull request merged**
