### PR TITLE
test(rup): checklist con otros

### PR DESCRIPTION
**Pull request by liquid36**
### Requerimiento
Casos de test para poder elegir otros
 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3014](http://condorpiedra.andes.gob.ar:85/3014/mochawesome.html)
CYPRESS RUN: [2141](https://dashboard.cypress.io/projects/xr7gft/runs/2141/specs)
TEST START: 2021-01-05T16:35:14.090Z
TOTAL: 351
SUCCESS: 350
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3015](http://condorpiedra.andes.gob.ar:85/3015/mochawesome.html)
CYPRESS RUN: [2142](https://dashboard.cypress.io/projects/xr7gft/runs/2142/specs)
TEST START: 2021-01-05T16:47:52.592Z
TOTAL: 351
SUCCESS: 350
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3017](http://condorpiedra.andes.gob.ar:85/3017/mochawesome.html)
CYPRESS RUN: [2144](https://dashboard.cypress.io/projects/xr7gft/runs/2144/specs)
TEST START: 2021-01-05T17:22:05.167Z
TOTAL: 351
SUCCESS: 349
FAIL: 2
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: mbotta  
BUILD NUMBER: [3018](http://condorpiedra.andes.gob.ar:85/3018/mochawesome.html)
CYPRESS RUN: [2145](https://dashboard.cypress.io/projects/xr7gft/runs/2145/specs)
TEST START: 2021-01-05T17:48:07.750Z
TOTAL: 351
SUCCESS: 351
FAIL: 0
SKIPPED: 0

**Review by palita1991 — APPROVED** [review]

**Pull request merged**
