### PR TITLE
IN - Ingreso en cama bloqueada

### PR DESCRIPTION
**Pull request by negro89**
### Funcionalidad desarrollada 

1. Corrige get de plex-button para edicion de internación, que fallaba cada tanto.

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7769](http://condorpiedra.andes.gob.ar:85/7769/mochawesome.html)
CYPRESS RUN: [6907](https://dashboard.cypress.io/projects/xr7gft/runs/6907/specs)
TEST START: 2022-10-18T14:58:46.993Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7771](http://condorpiedra.andes.gob.ar:85/7771/mochawesome.html)
CYPRESS RUN: [6909](https://dashboard.cypress.io/projects/xr7gft/runs/6909/specs)
TEST START: 2022-10-18T15:32:36.722Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7772](http://condorpiedra.andes.gob.ar:85/7772/mochawesome.html)
CYPRESS RUN: [6910](https://dashboard.cypress.io/projects/xr7gft/runs/6910/specs)
TEST START: 2022-10-18T15:55:52.331Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7773](http://condorpiedra.andes.gob.ar:85/7773/mochawesome.html)
CYPRESS RUN: [6911](https://dashboard.cypress.io/projects/xr7gft/runs/6911/specs)
TEST START: 2022-10-18T16:48:02.510Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7777](http://condorpiedra.andes.gob.ar:85/7777/mochawesome.html)
CYPRESS RUN: [6915](https://dashboard.cypress.io/projects/xr7gft/runs/6915/specs)
TEST START: 2022-10-18T17:46:05.704Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7779](http://condorpiedra.andes.gob.ar:85/7779/mochawesome.html)
CYPRESS RUN: [6917](https://dashboard.cypress.io/projects/xr7gft/runs/6917/specs)
TEST START: 2022-10-18T18:15:23.086Z
TOTAL: 2
SUCCESS: 1
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7781](http://condorpiedra.andes.gob.ar:85/7781/mochawesome.html)
CYPRESS RUN: [6919](https://dashboard.cypress.io/projects/xr7gft/runs/6919/specs)
TEST START: 2022-10-18T18:31:41.391Z
TOTAL: 2
SUCCESS: 2
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7783](http://condorpiedra.andes.gob.ar:85/7783/mochawesome.html)
CYPRESS RUN: [6921](https://dashboard.cypress.io/projects/xr7gft/runs/6921/specs)
TEST START: 2022-10-18T21:25:23.797Z
TOTAL: 323
SUCCESS: 315
FAIL: 7
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [7784](http://condorpiedra.andes.gob.ar:85/7784/mochawesome.html)
CYPRESS RUN: [6922](https://dashboard.cypress.io/projects/xr7gft/runs/6922/specs)
TEST START: 2022-10-18T21:37:11.805Z
TOTAL: 406
SUCCESS: 397
FAIL: 8
SKIPPED: 1

**Review by MCele — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: cramos  
BUILD NUMBER: [7788](http://condorpiedra.andes.gob.ar:85/7788/mochawesome.html)
CYPRESS RUN: [6926](https://dashboard.cypress.io/projects/xr7gft/runs/6926/specs)
TEST START: 2022-10-19T12:41:24.143Z
TOTAL: 361
SUCCESS: 352
FAIL: 8
SKIPPED: 1

**Pull request merged**
