### PR TITLE
Fix - Casos de tests no detectados en ultimos merges

### PR DESCRIPTION
**Pull request by negro89**
### Funcionalidad desarrollada 

1. Se fixean casos en el gestor, egreso en capa estadistica y bi-queries 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8440](http://condorpiedra.andes.gob.ar:85/8440/mochawesome.html)
CYPRESS RUN: [7615](https://dashboard.cypress.io/projects/xr7gft/runs/7615/specs)
TEST START: 2023-02-24T16:14:55.535Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8441](http://condorpiedra.andes.gob.ar:85/8441/mochawesome.html)
CYPRESS RUN: [7616](https://dashboard.cypress.io/projects/xr7gft/runs/7616/specs)
TEST START: 2023-02-24T17:16:05.971Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8442](http://condorpiedra.andes.gob.ar:85/8442/mochawesome.html)
CYPRESS RUN: [7617](https://dashboard.cypress.io/projects/xr7gft/runs/7617/specs)
TEST START: 2023-02-24T17:19:59.465Z
TOTAL: 368
SUCCESS: 341
FAIL: 25
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8443](http://condorpiedra.andes.gob.ar:85/8443/mochawesome.html)
CYPRESS RUN: [7618](https://dashboard.cypress.io/projects/xr7gft/runs/7618/specs)
TEST START: 2023-02-24T17:57:20.751Z
TOTAL: 406
SUCCESS: 396
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8444](http://condorpiedra.andes.gob.ar:85/8444/mochawesome.html)
CYPRESS RUN: [7619](https://dashboard.cypress.io/projects/xr7gft/runs/7619/specs)
TEST START: 2023-02-24T18:03:48.872Z
TOTAL: 323
SUCCESS: 277
FAIL: 44
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8445](http://condorpiedra.andes.gob.ar:85/8445/mochawesome.html)
CYPRESS RUN: [7620](https://dashboard.cypress.io/projects/xr7gft/runs/7620/specs)
TEST START: 2023-02-24T18:38:43.711Z
TOTAL: 395
SUCCESS: 377
FAIL: 16
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8446](http://condorpiedra.andes.gob.ar:85/8446/mochawesome.html)
CYPRESS RUN: [7621](https://dashboard.cypress.io/projects/xr7gft/runs/7621/specs)
TEST START: 2023-02-24T18:55:50.151Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8447](http://condorpiedra.andes.gob.ar:85/8447/mochawesome.html)
CYPRESS RUN: [7622](https://dashboard.cypress.io/projects/xr7gft/runs/7622/specs)
TEST START: 2023-02-24T19:16:32.585Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Review by MCele — APPROVED** [review]

**Pull request merged**
