### PR TITLE
fix(IN-447): Correccion de test en internacion

### PR DESCRIPTION
**Pull request by MarianoCampetella**
### Requerimiento
https://proyectos.andes.gob.ar/browse/IN-447

### Funcionalidad desarrollada 

1. Se corrigieron los test de internacion y por el momento se omitió un test hasta que se resuelva un bug que ocurre en la capa de estadística nueva. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by martinebucarey** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [6621](http://condorpiedra.andes.gob.ar:85/6621/mochawesome.html)
CYPRESS RUN: [5476](https://dashboard.cypress.io/projects/xr7gft/runs/5476/specs)
TEST START: 2022-06-15T13:25:44.583Z
TOTAL: 409
SUCCESS: 405
FAIL: 2
SKIPPED: 2

**Comment by martinebucarey** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [6622](http://condorpiedra.andes.gob.ar:85/6622/mochawesome.html)
CYPRESS RUN: [5477](https://dashboard.cypress.io/projects/xr7gft/runs/5477/specs)
TEST START: 2022-06-15T13:51:45.100Z
TOTAL: 409
SUCCESS: 405
FAIL: 2
SKIPPED: 2

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6659](http://condorpiedra.andes.gob.ar:85/6659/mochawesome.html)
CYPRESS RUN: [5513](https://dashboard.cypress.io/projects/xr7gft/runs/5513/specs)
TEST START: 2022-06-23T19:47:08.464Z
TOTAL: 409
SUCCESS: 400
FAIL: 8
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6667](http://condorpiedra.andes.gob.ar:85/6667/mochawesome.html)
CYPRESS RUN: [5521](https://dashboard.cypress.io/projects/xr7gft/runs/5521/specs)
TEST START: 2022-06-24T19:04:40.116Z
TOTAL: 408
SUCCESS: 400
FAIL: 7
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6668](http://condorpiedra.andes.gob.ar:85/6668/mochawesome.html)
CYPRESS RUN: [5522](https://dashboard.cypress.io/projects/xr7gft/runs/5522/specs)
TEST START: 2022-06-24T19:17:44.198Z
TOTAL: 408
SUCCESS: 402
FAIL: 5
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6674](http://condorpiedra.andes.gob.ar:85/6674/mochawesome.html)
CYPRESS RUN: [5528](https://dashboard.cypress.io/projects/xr7gft/runs/5528/specs)
TEST START: 2022-06-28T11:19:58.957Z
TOTAL: 408
SUCCESS: 397
FAIL: 10
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6675](http://condorpiedra.andes.gob.ar:85/6675/mochawesome.html)
CYPRESS RUN: [5529](https://dashboard.cypress.io/projects/xr7gft/runs/5529/specs)
TEST START: 2022-06-28T11:44:28.027Z
TOTAL: 390
SUCCESS: 384
FAIL: 5
SKIPPED: 1

**Comment by martinebucarey** [comment]
USUARIO: cramos  
BUILD NUMBER: [6679](http://condorpiedra.andes.gob.ar:85/6679/mochawesome.html)
CYPRESS RUN: [5533](https://dashboard.cypress.io/projects/xr7gft/runs/5533/specs)
TEST START: 2022-06-28T12:57:10.949Z
TOTAL: 408
SUCCESS: 405
FAIL: 2
SKIPPED: 1

**Review by MCele — APPROVED** [review]

**Pull request merged**
