### PR TITLE
test form-builder

### PR DESCRIPTION
**Pull request by plammel**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/EP-20

Test form builder. Correr con https://github.com/andes/app/pull/2219
### Funcionalidad desarrollada 

1. 
2. 
3. 

### Requiere actualizaciones en la base de datos

- [x] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3755](http://condorpiedra.andes.gob.ar:85/3755/mochawesome.html)
CYPRESS RUN: [2821](https://dashboard.cypress.io/projects/xr7gft/runs/2821/specs)
TEST START: 2021-04-13T16:44:00.323Z
TOTAL: 364
SUCCESS: 363
FAIL: 1
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3757](http://condorpiedra.andes.gob.ar:85/3757/mochawesome.html)
CYPRESS RUN: [2823](https://dashboard.cypress.io/projects/xr7gft/runs/2823/specs)
TEST START: 2021-04-13T17:17:03.609Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3759](http://condorpiedra.andes.gob.ar:85/3759/mochawesome.html)
CYPRESS RUN: [2824](https://dashboard.cypress.io/projects/xr7gft/runs/2824/specs)
TEST START: undefined
TOTAL: 0
SUCCESS: 0
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3760](http://condorpiedra.andes.gob.ar:85/3760/mochawesome.html)
CYPRESS RUN: [2825](https://dashboard.cypress.io/projects/xr7gft/runs/2825/specs)
TEST START: 2021-04-13T17:53:42.130Z
TOTAL: 1
SUCCESS: 0
FAIL: 1
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3770](http://condorpiedra.andes.gob.ar:85/3770/mochawesome.html)
CYPRESS RUN: [2835](https://dashboard.cypress.io/projects/xr7gft/runs/2835/specs)
TEST START: 2021-04-15T16:24:38.906Z
TOTAL: 334
SUCCESS: 320
FAIL: 14
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3775](http://condorpiedra.andes.gob.ar:85/3775/mochawesome.html)
CYPRESS RUN: [2840](https://dashboard.cypress.io/projects/xr7gft/runs/2840/specs)
TEST START: 2021-04-15T18:07:07.270Z
TOTAL: 1
SUCCESS: 1
FAIL: 0
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [3784](http://condorpiedra.andes.gob.ar:85/3784/mochawesome.html)
CYPRESS RUN: [2849](https://dashboard.cypress.io/projects/xr7gft/runs/2849/specs)
TEST START: 2021-04-16T13:28:37.696Z
TOTAL: 367
SUCCESS: 367
FAIL: 0
SKIPPED: 0

**Review by sychus — APPROVED** [review]

**Pull request merged**
