### PR TITLE
EP: registrar concepto c19 confirmado

### PR DESCRIPTION
**Pull request by plammel**
### Funcionalidad desarrollada 

1. 
2. 
3. 

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### CODE REVIEW

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5120](http://condorpiedra.andes.gob.ar:85/5120/mochawesome.html)
CYPRESS RUN: [4078](https://dashboard.cypress.io/projects/xr7gft/runs/4078/specs)
TEST START: 2021-09-21T15:29:25.428Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5169](http://condorpiedra.andes.gob.ar:85/5169/mochawesome.html)
CYPRESS RUN: [4119](https://dashboard.cypress.io/projects/xr7gft/runs/4119/specs)
TEST START: 2021-09-24T17:25:15.674Z
TOTAL: 393
SUCCESS: 381
FAIL: 11
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: martinebucarey  
BUILD NUMBER: [5170](http://condorpiedra.andes.gob.ar:85/5170/mochawesome.html)
CYPRESS RUN: [4120](https://dashboard.cypress.io/projects/xr7gft/runs/4120/specs)
TEST START: 2021-09-24T18:55:26.883Z
TOTAL: 401
SUCCESS: 398
FAIL: 2
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5177](http://condorpiedra.andes.gob.ar:85/5177/mochawesome.html)
CYPRESS RUN: [4125](https://dashboard.cypress.io/projects/xr7gft/runs/4125/specs)
TEST START: 2021-09-28T13:46:34.938Z
TOTAL: 398
SUCCESS: 387
FAIL: 11
SKIPPED: 0

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5183](http://condorpiedra.andes.gob.ar:85/5183/mochawesome.html)
CYPRESS RUN: [4131](https://dashboard.cypress.io/projects/xr7gft/runs/4131/specs)
TEST START: 2021-09-28T17:36:39.843Z
TOTAL: 393
SUCCESS: 391
FAIL: 1
SKIPPED: 1

**Comment by liquid36** [comment]
USUARIO: plammel  
BUILD NUMBER: [5185](http://condorpiedra.andes.gob.ar:85/5185/mochawesome.html)
CYPRESS RUN: [4132](https://dashboard.cypress.io/projects/xr7gft/runs/4132/specs)
TEST START: 2021-09-28T18:29:51.447Z
TOTAL: 401
SUCCESS: 400
FAIL: 0
SKIPPED: 1

**Review by palita1991 — APPROVED** [review]

**Pull request merged**
