### PR TITLE
MISC - Agregar alias y documento extranjero a datos de paciente

### PR DESCRIPTION
**Pull request by negro89**
### Requerimiento
https://proyectos.andes.gob.ar/browse/MISC-226

### Funcionalidad desarrollada 

1. Se actualizan funciones/operadores cypress deprecados y se adecua algun response a los cambios de la funcionalidad.

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8070](http://condorpiedra.andes.gob.ar:85/8070/mochawesome.html)
CYPRESS RUN: [7262](https://dashboard.cypress.io/projects/xr7gft/runs/7262/specs)
TEST START: 2022-12-02T19:05:04.042Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8081](http://condorpiedra.andes.gob.ar:85/8081/mochawesome.html)
CYPRESS RUN: [7273](https://dashboard.cypress.io/projects/xr7gft/runs/7273/specs)
TEST START: 2022-12-05T14:12:45.486Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8082](http://condorpiedra.andes.gob.ar:85/8082/mochawesome.html)
CYPRESS RUN: [7274](https://dashboard.cypress.io/projects/xr7gft/runs/7274/specs)
TEST START: 2022-12-05T14:38:24.180Z
TOTAL: 406
SUCCESS: 374
FAIL: 30
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8084](http://condorpiedra.andes.gob.ar:85/8084/mochawesome.html)
CYPRESS RUN: [7276](https://dashboard.cypress.io/projects/xr7gft/runs/7276/specs)
TEST START: 2022-12-05T15:23:39.796Z
TOTAL: 333
SUCCESS: 301
FAIL: 30
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8087](http://condorpiedra.andes.gob.ar:85/8087/mochawesome.html)
CYPRESS RUN: [7279](https://dashboard.cypress.io/projects/xr7gft/runs/7279/specs)
TEST START: 2022-12-05T16:40:30.900Z
TOTAL: 388
SUCCESS: 362
FAIL: 24
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8607](http://condorpiedra.andes.gob.ar:85/8607/mochawesome.html)
CYPRESS RUN: [7785](https://dashboard.cypress.io/projects/xr7gft/runs/7785/specs)
TEST START: 2023-03-21T15:35:26.496Z
TOTAL: 406
SUCCESS: 380
FAIL: 24
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8703](http://condorpiedra.andes.gob.ar:85/8703/mochawesome.html)
CYPRESS RUN: [7878](https://dashboard.cypress.io/projects/xr7gft/runs/7878/specs)
TEST START: 2023-04-13T18:15:22.497Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8709](http://condorpiedra.andes.gob.ar:85/8709/mochawesome.html)
CYPRESS RUN: [7884](https://dashboard.cypress.io/projects/xr7gft/runs/7884/specs)
TEST START: 2023-04-13T19:38:37.287Z
TOTAL: 372
SUCCESS: 356
FAIL: 14
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8711](http://condorpiedra.andes.gob.ar:85/8711/mochawesome.html)
CYPRESS RUN: [7886](https://dashboard.cypress.io/projects/xr7gft/runs/7886/specs)
TEST START: 2023-04-14T14:02:54.490Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8712](http://condorpiedra.andes.gob.ar:85/8712/mochawesome.html)
CYPRESS RUN: [7887](https://dashboard.cypress.io/projects/xr7gft/runs/7887/specs)
TEST START: 2023-04-14T14:18:54.136Z
TOTAL: 232
SUCCESS: 181
FAIL: 50
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8713](http://condorpiedra.andes.gob.ar:85/8713/mochawesome.html)
CYPRESS RUN: [7888](https://dashboard.cypress.io/projects/xr7gft/runs/7888/specs)
TEST START: 2023-04-14T15:02:24.760Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8772](http://condorpiedra.andes.gob.ar:85/8772/mochawesome.html)
CYPRESS RUN: [7943](https://dashboard.cypress.io/projects/xr7gft/runs/7943/specs)
TEST START: 2023-04-26T17:32:22.816Z
TOTAL: 406
SUCCESS: 381
FAIL: 23
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8774](http://condorpiedra.andes.gob.ar:85/8774/mochawesome.html)
CYPRESS RUN: [7945](https://dashboard.cypress.io/projects/xr7gft/runs/7945/specs)
TEST START: 2023-04-26T18:27:10.722Z
TOTAL: 312
SUCCESS: 279
FAIL: 31
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8776](http://condorpiedra.andes.gob.ar:85/8776/mochawesome.html)
CYPRESS RUN: [7947](https://dashboard.cypress.io/projects/xr7gft/runs/7947/specs)
TEST START: 2023-04-26T19:27:42.211Z
TOTAL: 398
SUCCESS: 371
FAIL: 25
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8788](http://condorpiedra.andes.gob.ar:85/8788/mochawesome.html)
CYPRESS RUN: [7958](https://dashboard.cypress.io/projects/xr7gft/runs/7958/specs)
TEST START: 2023-04-27T16:03:49.285Z
TOTAL: 398
SUCCESS: 367
FAIL: 29
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8807](http://condorpiedra.andes.gob.ar:85/8807/mochawesome.html)
CYPRESS RUN: [7977](https://dashboard.cypress.io/projects/xr7gft/runs/7977/specs)
TEST START: 2023-05-02T12:59:52.285Z
TOTAL: 262
SUCCESS: 232
FAIL: 28
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8808](http://condorpiedra.andes.gob.ar:85/8808/mochawesome.html)
CYPRESS RUN: [7978](https://dashboard.cypress.io/projects/xr7gft/runs/7978/specs)
TEST START: 2023-05-02T13:32:56.715Z
TOTAL: 406
SUCCESS: 401
FAIL: 3
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8833](http://condorpiedra.andes.gob.ar:85/8833/mochawesome.html)
CYPRESS RUN: [8002](https://dashboard.cypress.io/projects/xr7gft/runs/8002/specs)
TEST START: 2023-05-04T16:29:00.378Z
TOTAL: 356
SUCCESS: 286
FAIL: 68
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8834](http://condorpiedra.andes.gob.ar:85/8834/mochawesome.html)
CYPRESS RUN: [8003](https://dashboard.cypress.io/projects/xr7gft/runs/8003/specs)
TEST START: 2023-05-04T16:47:48.625Z
TOTAL: 406
SUCCESS: 337
FAIL: 67
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8865](http://condorpiedra.andes.gob.ar:85/8865/mochawesome.html)
CYPRESS RUN: [8032](https://dashboard.cypress.io/projects/xr7gft/runs/8032/specs)
TEST START: 2023-05-10T16:03:17.663Z
TOTAL: 406
SUCCESS: 402
FAIL: 2
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8866](http://condorpiedra.andes.gob.ar:85/8866/mochawesome.html)
CYPRESS RUN: [8033](https://dashboard.cypress.io/projects/xr7gft/runs/8033/specs)
TEST START: 2023-05-10T17:45:36.431Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8867](http://condorpiedra.andes.gob.ar:85/8867/mochawesome.html)
CYPRESS RUN: [8034](https://dashboard.cypress.io/projects/xr7gft/runs/8034/specs)
TEST START: 2023-05-10T17:59:55.941Z
TOTAL: 356
SUCCESS: 353
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8890](http://condorpiedra.andes.gob.ar:85/8890/mochawesome.html)
CYPRESS RUN: [8055](https://dashboard.cypress.io/projects/xr7gft/runs/8055/specs)
TEST START: 2023-05-15T13:59:01.061Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: lmlagos  
BUILD NUMBER: [8896](http://condorpiedra.andes.gob.ar:85/8896/mochawesome.html)
CYPRESS RUN: [8061](https://dashboard.cypress.io/projects/xr7gft/runs/8061/specs)
TEST START: 2023-05-15T16:30:03.411Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Pull request merged**
