### PR TITLE
MAT - Pantalla creacion usuario

### PR DESCRIPTION
**Pull request by JuanIRamirez**
### Requerimiento
 
https://proyectos.andes.gob.ar/browse/MAT-151

### Funcionalidad desarrollada 

1. Se corrigió test: Crear usuario para profesional.

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### CODE REVIEW

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9739](http://condorpiedra.andes.gob.ar:85/9739/mochawesome.html)
CYPRESS RUN: [8850](https://dashboard.cypress.io/projects/xr7gft/runs/8850/specs)
TEST START: 2023-10-05T12:42:16.049Z
TOTAL: 368
SUCCESS: 358
FAIL: 8
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9740](http://condorpiedra.andes.gob.ar:85/9740/mochawesome.html)
CYPRESS RUN: [8851](https://dashboard.cypress.io/projects/xr7gft/runs/8851/specs)
TEST START: 2023-10-05T13:34:22.351Z
TOTAL: 403
SUCCESS: 400
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: jramirez  
BUILD NUMBER: [9760](http://condorpiedra.andes.gob.ar:85/9760/mochawesome.html)
CYPRESS RUN: [8870](https://dashboard.cypress.io/projects/xr7gft/runs/8870/specs)
TEST START: 2023-10-10T13:38:25.822Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

**Review by MarianoCampetella — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [10155](http://condorpiedra.andes.gob.ar:85/10155/mochawesome.html)
CYPRESS RUN: [9263](https://dashboard.cypress.io/projects/xr7gft/runs/9263/specs)
TEST START: 2024-01-03T18:21:23.868Z
TOTAL: 406
SUCCESS: 403
FAIL: 1
SKIPPED: 2

**Review by Fabio-Ramirez — APPROVED** [review]

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [10162](http://condorpiedra.andes.gob.ar:85/10162/mochawesome.html)
CYPRESS RUN: [9270](https://dashboard.cypress.io/projects/xr7gft/runs/9270/specs)
TEST START: 2024-01-04T13:05:18.461Z
TOTAL: 388
SUCCESS: 385
FAIL: 1
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [10165](http://condorpiedra.andes.gob.ar:85/10165/mochawesome.html)
CYPRESS RUN: [9273](https://dashboard.cypress.io/projects/xr7gft/runs/9273/specs)
TEST START: 2024-01-04T13:51:02.547Z
TOTAL: 371
SUCCESS: 354
FAIL: 15
SKIPPED: 2

**Comment by silviroa** [comment]
USUARIO: mcampetella  
BUILD NUMBER: [10168](http://condorpiedra.andes.gob.ar:85/10168/mochawesome.html)
CYPRESS RUN: [9276](https://dashboard.cypress.io/projects/xr7gft/runs/9276/specs)
TEST START: 2024-01-04T14:52:52.666Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

**Pull request merged**
